// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB34Mrx8_c6lOkZ8OgdQEnMkAv__pg5CdM',
    appId: '1:76626943099:web:eac0851dbdf4c713db56de',
    messagingSenderId: '76626943099',
    projectId: 'recapnote-0511',
    authDomain: 'recapnote-0511.firebaseapp.com',
    storageBucket: 'recapnote-0511.firebasestorage.app',
    measurementId: 'G-4DNLJLY0MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5P56GHol9MrHBiPcEaPwHm7ml3JkUcSo',
    appId: '1:76626943099:android:3feecfe9a9ce49c8db56de',
    messagingSenderId: '76626943099',
    projectId: 'recapnote-0511',
    storageBucket: 'recapnote-0511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzZ65ijaFnLWRVflRgtva0GX_pWMK17rw',
    appId: '1:76626943099:ios:c321c7da206d7ab7db56de',
    messagingSenderId: '76626943099',
    projectId: 'recapnote-0511',
    storageBucket: 'recapnote-0511.firebasestorage.app',
    iosBundleId: 'com.example.recapnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzZ65ijaFnLWRVflRgtva0GX_pWMK17rw',
    appId: '1:76626943099:ios:c321c7da206d7ab7db56de',
    messagingSenderId: '76626943099',
    projectId: 'recapnote-0511',
    storageBucket: 'recapnote-0511.firebasestorage.app',
    iosBundleId: 'com.example.recapnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB34Mrx8_c6lOkZ8OgdQEnMkAv__pg5CdM',
    appId: '1:76626943099:web:88638e6472c9d39ddb56de',
    messagingSenderId: '76626943099',
    projectId: 'recapnote-0511',
    authDomain: 'recapnote-0511.firebaseapp.com',
    storageBucket: 'recapnote-0511.firebasestorage.app',
    measurementId: 'G-98DY5KFMG6',
  );
}
